---
- name: install elk
  hosts: elk
  become: true
  tasks:
    - name: Install docker.io
      apt:
        force_apt_get: yes     
        name: docker.io
        state: present
        update_cache: yes

    - name: Install python3-pip 
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: Install Docker Module
      pip:
        name: docker
        state: present

    - name: Increase virtual mem
      command: sysctl -w vm.max_map_count=262144

    - name: Use more mem
      sysctl:
        name: vm.max_map_count
        reload: yes
        state: present
        value: '262144'

    - name: download and launch docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044