---
- name: installing and launching metricbeat
  hosts: elk
  become: yes
  tasks:
  - name: download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb
  - name: install metricbeat deb
    command: dpkg -i metricbeat-7.4.0-amd64.deb
  - name: drop in metricbeat config
    copy:
      src: /etc/ansible/roles/metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml
  - name: enable docker command
    command: metricbeat modules enable docker
  - name: setup metricbeat
    command: metricbeat setup
  - name: metricbeat -e
    command: metricbeat run -e